name: CI Pipeline

on:
  push:
    branches:
      - master  # Ejecuta en push a master
  pull_request:
    branches:
      - master  # Ejecuta en pull requests a master

jobs:
  build:
    runs-on: ubuntu-latest  # Usa una máquina virtual Ubuntu

    steps:
      - name: Checkout code  # Clona el código del repositorio
        uses: actions/checkout@v3  # Actualiza a la versión 3

      - name: Set up Node.js  # Configura Node.js
        uses: actions/setup-node@v3  # Actualiza a la versión 3
        with:
          node-version: '20'  # Establece la versión de Node.js (puede ser otra versión compatible)

      - name: Install dependencies  # Instala las dependencias
        run: npm install

      - name: Run lint  # Verifica el estilo del código con eslint
        run: npm run lint

      - name: Run tests  # Ejecuta las pruebas de tu proyecto
        run: npm run test

      - name: Build the project  # Construye el proyecto si todo pasa
        run: npm run build
